### ISSUE TITLE
Incompatibility with latest Grade 6.6

### ISSUE THREAD

**Issue by inceptiona7** [GoogleCloudPlatform/artifact-registry-maven-tools#35]
using `classpath "gradle.plugin.com.google.cloud.artifactregistry:artifactregistry-gradle-plugin:2.1.0"`
```
* What went wrong:
A problem occurred configuring root project
> Failed to notify project evaluation listener.
   > org.gradle.api.internal.artifacts.repositories.DefaultMavenArtifactRepository.getConfiguredCredentials()Lorg/gradle/api/credentials/Credentials;
```
The partial root cause stack trace is 
```
Caused by: java.lang.NoSuchMethodError: org.gradle.api.internal.artifacts.repositories.DefaultMavenArtifactRepository.getConfiguredCredentials()Lorg/gradle/api/credentials/Credentials;
        at com.google.cloud.artifactregistry.gradle.plugin.ArtifactRegistryGradlePlugin.configureArtifactRegistryRepository(ArtifactRegistryGradlePlugin.java:143)
        at com.google.cloud.artifactregistry.gradle.plugin.ArtifactRegistryGradlePlugin.lambda$modifyProject$4(ArtifactRegistryGradlePlugin.java:114)
        at com.google.cloud.artifactregistry.gradle.plugin.ArtifactRegistryGradlePlugin.modifyProject(ArtifactRegistryGradlePlugin.java:114)
        at com.google.cloud.artifactregistry.gradle.plugin.ArtifactRegistryGradlePlugin.lambda$applyProject$3(ArtifactRegistryGradlePlugin.java:110)
        at org.gradle.configuration.internal.DefaultUserCodeApplicationContext$CurrentApplication$1.execute(DefaultUserCodeApplicationContext.java:100)
        at org.gradle.configuration.internal.DefaultListenerBuildOperationDecorator$BuildOperationEmittingAction$1.run(DefaultListenerBuildOperationDecorator.java:153)
```
The plugin works file with the Gradle 6.5.1

It looks like the return type was changed as a part of the [https://github.com/gradle/gradle/commit/edaee4d572bd6c699cc8b8f1cda0012681443949#diff-cceda20d70f6ca7d4c5f90667c23f4ec](https://github.com/gradle/gradle/commit/edaee4d572bd6c699cc8b8f1cda0012681443949#diff-cceda20d70f6ca7d4c5f90667c23f4ec)

I think just a recompile with the latest version will do.

**Comment by asodja** [comment]
I see that fix is already on master https://github.com/GoogleCloudPlatform/artifact-registry-maven-tools/pull/37. Is there any plan to release next plugin version soon? :)

**Comment by lindsayismith** [comment]
The PR in #37 was released in version 2.1.1 - can you try that?

**Comment by asodja** [comment]
Tested with Gradle 6.4.1 and 6.7 and I can confirm that it works on both version. Awesome, thank you!

**Comment by lindsayismith** [comment]
Excellent thanks for letting us know.
