### ISSUE TITLE
Request contains an invalid argument. when using + in the version

### ISSUE THREAD

**Issue by MasseGuillaume** [GoogleCloudPlatform/artifact-registry-maven-tools#41]
I was trying to push an artifact with a + in the version

eg: `magento-graphql-scala_2.12-0.2.0+675fbbd9.pom`

```
[error] org.apache.maven.wagon.TransferFailedException: Received an error from the remote server.
[error]         at com.google.cloud.artifactregistry.wagon.ArtifactRegistryWagon.handlePutRequest(ArtifactRegistryWagon.java:176)
[error]         at com.google.cloud.artifactregistry.wagon.ArtifactRegistryWagon.put(ArtifactRegistryWagon.java:202)
[error]         at ch.firsts.sbt.gar.ArtifactRegistryRepository.put(ArtifactRegistryRepository.scala:38)
[error]         at org.apache.ivy.plugins.resolver.RepositoryResolver.put(RepositoryResolver.java:234)
[error]         at org.apache.ivy.plugins.resolver.RepositoryResolver.publish(RepositoryResolver.java:216)
[error]         at sbt.internal.librarymanagement.IvyActions$.$anonfun$publish$5(IvyActions.scala:501)
[error]         at sbt.internal.librarymanagement.IvyActions$.$anonfun$publish$5$adapted(IvyActions.scala:500)
[error]         at scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:877)
[error]         at scala.collection.Iterator.foreach(Iterator.scala:941)
[error]         at scala.collection.Iterator.foreach$(Iterator.scala:941)
[error]         at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
[error]         at scala.collection.IterableLike.foreach(IterableLike.scala:74)
[error]         at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
[error]         at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
[error]         at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:876)
[error]         at sbt.internal.librarymanagement.IvyActions$.publish(IvyActions.scala:500)
```

I'm using https://github.com/SupraFii/sbt-google-artifact-registry but looking at the code, I don't see anything wrong in the wrapper.

**Comment by Gridasov** [comment]
Could you provide the full URL that is published and the debug log?
I checked - we are accepting the "+" character in the filename.

**Comment by lindsayismith** [comment]
Since we haven't had a response we're closing this - please reopen with more details if you are still affected.
